---
- name: Install HAProxy
  ansible.builtin.dnf:
    name: haproxy
    state: present

- name: Configure HAProxy
  ansible.builtin.template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: Restart HAProxy

- name: Enable and start HAProxy
  ansible.builtin.systemd:
    name: haproxy
    state: started
    enabled: yes

- name: Ensure HAProxy is running
  ansible.builtin.systemd:
    name: haproxy
    state: started
