---
- name: Install HAProxy
  yum:
    name: haproxy
    state: present
  become: yes
  delegate_to: "{{ target_host }}"

- name: Configure HAProxy
  template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  become: yes
  delegate_to: "{{ target_host }}"
  notify: Restart HAProxy

- name: Enable and start HAProxy
  systemd:
    name: haproxy
    state: started
    enabled: yes
  become: yes
  delegate_to: "{{ target_host }}"

- name: Restart HAProxy
  systemd:
    name: haproxy
    state: restarted
  become: yes
  delegate_to: "{{ target_host }}"
  listen: Restart HAProxy
