---
- name: Debug - Starting destroy task
  debug:
    msg: "Beginning VM destruction process"

- name: Destroy VMs
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    name: "{{ item.name }}"
    state: absent
    force: yes
  loop: "{{ vm_specs }}"
  register: destroy_result

- name: Debug - Destroy result
  debug:
    var: destroy_result

- name: Remove VMs from inventory
  meta: refresh_inventory

- name: Debug - Finished destroy task
  debug:
    msg: "VM destruction process completed"