- name: Deploy Load Balanced Web Application in VMware
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../group_vars/all.yml
  tasks:
    - name: Include VM provisioning tasks
      include_tasks: tasks/provision_vms.yml

    - name: Include HAProxy configuration tasks
      include_tasks: tasks/configure_haproxy.yml

    - name: Include Web Server configuration tasks
      include_tasks: tasks/configure_webservers.yml

    - name: Include Database configuration tasks
      include_tasks: tasks/configure_database.yml

    - name: Display server information
      include_tasks: tasks/display_info.ym
