---
- name: Deploy or Destroy Load Balanced Web Application in VMware
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../group_vars/all.yml
  tasks:
    - name: Initial Debug
      debug:
        msg: "Playbook started execution"

    - name: Debug variables
      debug:
        msg: 
          - "destroy_deployment: {{ destroy_deployment | default(false) }}"
          - "All variables: {{ vars | to_nice_yaml }}"

    - name: Pre-condition Debug
      debug:
        msg: "About to check conditions"

    - name: Run deployment tasks
      block:
        - name: Debug - Entering deployment block
          debug:
            msg: "Starting deployment tasks"
        - name: Include VM provisioning tasks
          include_tasks: tasks/provision_vms.yml
        - name: Include HAProxy configuration tasks
          include_tasks: tasks/configure_haproxy.yml
          become: yes
        - name: Include Web Server configuration tasks
          include_tasks: tasks/configure_webservers.yml
          become: yes
        - name: Include Database configuration tasks
          include_tasks: tasks/configure_database.yml
          become: yes
        - name: Display server information
          include_tasks: tasks/display_info.yml
        - name: Debug - Completed deployment block
          debug:
            msg: "Finished deployment tasks"
      when: not (destroy_deployment | default(false) | bool)

    - name: Post-deployment Debug
      debug:
        msg: "Deployment block complete, checking destroy condition"

    - name: Destroy Deployment
      block:
        - name: Debug - Entering destroy block
          debug:
            msg: "Starting destroy tasks"
        - name: Include destroy tasks
          include_tasks: tasks/destroy.yml
        - name: Debug - Completed destroy block
          debug:
            msg: "Finished destroy tasks"
      when: destroy_deployment | default(false) | bool

    - name: Final debug
      debug:
        msg: "Playbook execution completed"