---
- name: Deploy or Destroy Load Balanced Web Application in VMware
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../group_vars/all.yml
  tasks:
    - name: Debug variables
      ansible.builtin.debug:
        msg: 
          - "destroy_deployment: {{ destroy_deployment | default(false) }}"
          - "All variables: {{ vars | to_nice_yaml }}"

    - name: Run deployment tasks
      when: not (destroy_deployment | default(false) | bool)
      block:
        - name: Include VM provisioning tasks
          ansible.builtin.include_tasks:
            file: tasks/provision_vms.yml

        - name: Configure HAProxy
          ansible.builtin.include_tasks:
            file: tasks/configure_haproxy.yml
            apply:
              become: yes
          loop: "{{ groups['haproxy'] }}"
          vars:
            ansible_host: "{{ item }}"

        - name: Include Web Server configuration tasks
          ansible.builtin.include_tasks:
            file: tasks/configure_webservers.yml
            apply:
              become: yes
          loop: "{{ groups['webserver'] }}"
          vars:
            ansible_host: "{{ item }}"

        - name: Include Database configuration tasks
          ansible.builtin.include_tasks:
            file: tasks/configure_database.yml
            apply:
              become: yes
          loop: "{{ groups['database'] }}"
          vars:
            ansible_host: "{{ item }}"

        - name: Display server information
          ansible.builtin.include_tasks:
            file: tasks/display_info.yml

    - name: Run destruction tasks
      ansible.builtin.include_tasks:
        file: tasks/destroy.yml
      when: destroy_deployment | default(false) | bool

    - name: Final debug
      ansible.builtin.debug:
        msg: "Playbook execution completed"
